---====================---
---Feasibility Analysis
---====================---

---===============================================---
---Table 1: AATD-related Emphysema Patients Cohort
---===============================================---


---===================================================================---
---1.1 Patients observable in the database on or after January 1, 2016
---===================================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503
LIMIT 10;


---Descriotion : Here we are looking into the data table below
---"PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503" and listing the distinct patients
---who have enrolled in the insurance after '2016-01-01'

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1 AS
SELECT DISTINCT ENROLID 
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503
WHERE CONT_ENR_START_DT >= '2016-01-01';

SELECT COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1;

--PATS
--95443760


---===================================================================================================---
---1.2 Patients with ≥1 inpatient claim OR ≥2 outpatient claims (≥30 days apart and ≤365 days between) 
---with a diagnosis of AATD (ICD-10-CM: E88.01)
---===================================================================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 LIMIT 10;

SELECT DISTINCT POS_CATEGORY FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 LIMIT 10;


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1 AS
WITH BASE_PATIENTS AS (
    SELECT DISTINCT ENROLID
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1
),

AATD_CLAIMS AS (
    SELECT ENROLID, DX_DT, POS_CATEGORY
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503
    WHERE DX LIKE 'E8801%'
      AND ENROLID IN (SELECT ENROLID FROM BASE_PATIENTS)
),

-- PATIENTS WITH >=1 INPATIENT CLAIM
INPATIENT AS (
    SELECT ENROLID, DX_DT
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY IN ('ip')
),

-- PATIENTS WITH >=2 OUTPATIENT CLAIMS (>=30 DAYS APART AND <=365 DAYS BETWEEN)
OUTPATIENT_PAIRS AS (
    SELECT DISTINCT A.ENROLID, A.DX_DT
    FROM AATD_CLAIMS A
    JOIN AATD_CLAIMS B
      ON A.ENROLID = B.ENROLID
     AND A.POS_CATEGORY IN ('op', 'er', 'ltc', 'other')
     AND B.POS_CATEGORY IN ('op', 'er', 'ltc', 'other')
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
),
FINAL1 AS(
-- Combine both criteria
SELECT DISTINCT ENROLID, DX_DT
FROM INPATIENT
UNION ALL
SELECT DISTINCT ENROLID, DX_DT
FROM OUTPATIENT_PAIRS
)
SELECT ENROLID, MIN (DX_DT) AS AATD_DX_DT
FROM FINAL1
GROUP BY ENROLID
;




SELECT COUNT(*) AS COUNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1;

--COUNT	PATS
--9799	9799


SELECT *
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1
LIMIT 10;


---===============================================================---
---1.3. Patients age ≥18 years on the date of first AATD diagnosis---
---===============================================================---

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1 AS
SELECT DISTINCT
    A.ENROLID,
    A.AATD_DX_DT AS FIRST_AATD_DX_DATE,
    B.GENDER,
    B.DOBYR,
    (YEAR(A.AATD_DX_DT) - B.DOBYR) AS AGE_AT_DIAGNOSIS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1 A
INNER JOIN PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503 B
    ON A.ENROLID = B.ENROLID
WHERE (YEAR(A.AATD_DX_DT) - B.DOBYR) >= 18;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1;

--CNT	PATS
--8858	8856


SELECT *
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1
WHERE ENROLID IN ('20050861235', '20039580477')
;

---Here the above 2 patients recorded multiple Gender entries and hence I am excluding these 2 patients

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2 AS
SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1
WHERE ENROLID NOT IN ('20050861235', '20039580477');

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2;

--CNT	PATS
--8854	8854

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2 LIMIT 10;

---==============================================================================================---
---1.4. Patients with ≥1 claim with a diagnosis of emphysema (ICD-10-CM: J43.x) on or 
---any time before the FIRST AATD DIAGNOSIS DATE
---==============================================================================================---


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 AS
SELECT DISTINCT
    A.ENROLID,
    A.FIRST_AATD_DX_DATE,
    A.GENDER,
    A.DOBYR,
    A.AGE_AT_DIAGNOSIS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2 A
INNER JOIN PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503 B
    ON A.ENROLID = B.ENROLID
WHERE B.DX LIKE 'J43%'  -- Emphysema ICD-10-CM codes
  AND B.DX_DT <= A.FIRST_AATD_DX_DATE;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1;

--CNT	PATS
--1573	1573

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 LIMIT 10;


---======================================================================================================================---
---1.5. Patients whose first emphysema diagnosis occurs before or within 365 days following 
---the confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)
---======================================================================================================================---


---Step1 : Patient's first Emphysema :

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_SG_1 AS
WITH EMPHYSEMA_DX AS (
    SELECT
        ENROLID,
        DX_DT,
        DX,
        ROW_NUMBER() OVER (PARTITION BY ENROLID ORDER BY DX_DT ASC) AS RN
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503
    WHERE DX LIKE 'J43%'
)
SELECT
    C.ENROLID,
    C.FIRST_AATD_DX_DATE,
    C.GENDER,
    C.DOBYR,
    C.AGE_AT_DIAGNOSIS,
    E.DX_DT AS FIRST_EMPHYSEMA_DX_DATE,
    E.DX
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 C
JOIN EMPHYSEMA_DX E
    ON C.ENROLID = E.ENROLID
WHERE E.RN = 1;

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_SG_1;

--CNT	PATS
--1573	1573


---Step2 : Finding confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_CONFIRM_AATD_SG_1 AS
WITH AATD_CLAIMS AS (
    SELECT
        ENROLID,
        DX_DT,
        POS_CATEGORY
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503
    WHERE DX LIKE 'E8801%'
),
INPATIENT_CLAIMS AS (
    SELECT ENROLID, MIN(DX_DT) AS FIRST_INPATIENT_DATE
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY = 'ip'
    GROUP BY ENROLID
),
OUTPATIENT_CLAIMS AS (
    SELECT ENROLID, DX_DT
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY IN ('op', 'er', 'other', 'ltc')
),
OUTPATIENT_PAIRS AS (
    SELECT
        A.ENROLID,
        MIN(A.DX_DT) AS FIRST_OUTPATIENT_DATE,
        MIN(B.DX_DT) AS SECOND_OUTPATIENT_DATE
    FROM OUTPATIENT_CLAIMS A
    JOIN OUTPATIENT_CLAIMS B
        ON A.ENROLID = B.ENROLID
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
    GROUP BY a.ENROLID
)
SELECT
    E.ENROLID,
    E.FIRST_AATD_DX_DATE,
    E.GENDER,
    E.DOBYR,
    E.AGE_AT_DIAGNOSIS,
    E.FIRST_EMPHYSEMA_DX_DATE,
    I.FIRST_INPATIENT_DATE,
    O.FIRST_OUTPATIENT_DATE,
    O.SECOND_OUTPATIENT_DATE
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_SG_1 E
LEFT JOIN INPATIENT_CLAIMS I ON E.ENROLID = I.ENROLID
LEFT JOIN OUTPATIENT_PAIRS O ON E.ENROLID = O.ENROLID
WHERE I.FIRST_INPATIENT_DATE IS NOT NULL
   OR O.SECOND_OUTPATIENT_DATE IS NOT NULL;


SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_CONFIRM_AATD_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_CONFIRM_AATD_SG_1;

--CNT	PATS
--1573	1573

---Step3 : Finding the patients whose first emphysema diagnosis occurs before or 
--within 365 days following the confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_EMPHYSEMA_AATD_TIMING_SG_1 AS
SELECT
    ENROLID,
    FIRST_AATD_DX_DATE,
    FIRST_EMPHYSEMA_DX_DATE,
    FIRST_INPATIENT_DATE,
    SECOND_OUTPATIENT_DATE,
    CASE
        WHEN FIRST_EMPHYSEMA_DX_DATE <= DATEADD(day, 365, COALESCE(FIRST_INPATIENT_DATE, SECOND_OUTPATIENT_DATE))
        THEN 'YES'
        ELSE 'NO'
    END AS EMPHYSEMA_WITHIN_365_FLAG
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_FIRST_EMPHYSEMA_CONFIRM_AATD_SG_1
WHERE FIRST_EMPHYSEMA_DX_DATE <= DATEADD(day, 365, COALESCE(FIRST_INPATIENT_DATE, SECOND_OUTPATIENT_DATE));

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_EMPHYSEMA_AATD_TIMING_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_EMPHYSEMA_AATD_TIMING_SG_1
WHERE EMPHYSEMA_WITHIN_365_FLAG IN ('YES');

--CNT	PATS
--1573	1573

---============================================================================================================================---
---1.6. Patients with ≥1 inpatient or ≥2 outpatient claims (≥30 days apart and ≤365 days between) with a diagnosis of emphysema---
---============================================================================================================================---



CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1 AS
WITH EMPHYSEMA_CLAIMS AS (
    SELECT
        ENROLID,
        DX_DT,
        POS_CATEGORY
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503
    WHERE DX LIKE 'J43%'
),
INPATIENT_CLAIMS AS (
    SELECT ENROLID, MIN(DX_DT) AS FIRST_EMPHYSEMA_INPATIENT_DATE
    FROM EMPHYSEMA_CLAIMS
    WHERE POS_CATEGORY = 'ip'
    GROUP BY ENROLID
),
OUTPATIENT_CLAIMS AS (
    SELECT ENROLID, DX_DT
    FROM EMPHYSEMA_CLAIMS
    WHERE POS_CATEGORY IN ('op', 'er', 'other', 'ltc')
),
OUTPATIENT_PAIRS AS (
    SELECT
        A.ENROLID,
        MIN(a.DX_DT) AS FIRST_EMPHYSEMA_OUTPATIENT_DATE,
        MIN(b.DX_DT) AS SECOND_EMPHYSEMA_OUTPATIENT_DATE
    FROM OUTPATIENT_CLAIMS A
    JOIN OUTPATIENT_CLAIMS B
        ON A.ENROLID = B.ENROLID
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
    GROUP BY A.ENROLID
)
SELECT
    E.ENROLID,
    E.FIRST_AATD_DX_DATE,
    E.FIRST_EMPHYSEMA_DX_DATE,
    I.FIRST_EMPHYSEMA_INPATIENT_DATE,
    O.FIRST_EMPHYSEMA_OUTPATIENT_DATE,
    O.SECOND_EMPHYSEMA_OUTPATIENT_DATE
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.PATIENTS_EMPHYSEMA_AATD_TIMING_SG_1 E
LEFT JOIN INPATIENT_CLAIMS I ON E.ENROLID = I.ENROLID
LEFT JOIN OUTPATIENT_PAIRS O ON E.ENROLID = O.ENROLID
WHERE I.FIRST_EMPHYSEMA_INPATIENT_DATE IS NOT NULL
   OR O.SECOND_EMPHYSEMA_OUTPATIENT_DATE IS NOT NULL;


SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1;

--CNT	PATS
--1381	1381