---====================---
---Feasibility Analysis
---====================---

---===============================================---
---Table 1: AATD-related Emphysema Patients Cohort
---===============================================---


---===================================================================---
---1.1 Patients observable in the database on or after January 1, 2016
---===================================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503
LIMIT 10;


---Description : Here we are looking into the data table below
---"PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503" and listing the distinct patients
---who have enrolled in the insurance after '2016-01-01'

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1 AS
SELECT DISTINCT ENROLID, GENDER, DOBYR 
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503
WHERE CONT_ENR_START_DT >= '2016-01-01';

SELECT COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1;

--PATS
--95443760

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1 LIMIT 10;

---===================================================================================================---
---1.2 Patients with ≥1 inpatient claim OR ≥2 outpatient claims (≥30 days apart and ≤365 days between) 
---with a diagnosis of AATD (ICD-10-CM: E88.01)
---===================================================================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 LIMIT 10;

SELECT DISTINCT POS_CATEGORY FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 LIMIT 10;


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1 AS
WITH AATD_CLAIMS AS (
    SELECT B.ENROLID, A.DX_DT, A.POS_CATEGORY 
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503 AS A
    INNER JOIN 
         PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1 AS B
      ON A.ENROLID = B.ENROLID   
    WHERE A.DX LIKE 'E8801%'
),

-- PATIENTS WITH >=1 INPATIENT CLAIM
INPATIENT AS (
    SELECT ENROLID, DX_DT
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY IN ('ip')
),

-- PATIENTS WITH >=2 OUTPATIENT CLAIMS (>=30 DAYS APART AND <=365 DAYS BETWEEN)
OUTPATIENT_PAIRS AS (
    SELECT DISTINCT A.ENROLID, A.DX_DT
    FROM AATD_CLAIMS A
    JOIN AATD_CLAIMS B
      ON A.ENROLID = B.ENROLID
     AND A.POS_CATEGORY IN ('op', 'er', 'ltc', 'other')
     AND B.POS_CATEGORY IN ('op', 'er', 'ltc', 'other')
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
),
FINAL1 AS(
-- Combine both criteria
SELECT DISTINCT ENROLID, DX_DT
FROM INPATIENT
UNION ALL
SELECT DISTINCT ENROLID, DX_DT
FROM OUTPATIENT_PAIRS
),
FINAL2 AS (
SELECT ENROLID, MIN (DX_DT) AS AATD_DX_DT
FROM FINAL1
GROUP BY ENROLID
)
SELECT A.*, B.GENDER, B.DOBYR
FROM FINAL2 AS A
INNER JOIN 
PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_OBSRV_SG_1 AS B
ON A.ENROLID = B.ENROLID
;

---('20050861235', '20048536999', '20039580477', '20052475518', '20051103633') These patients have multiple gender or multiple DOBYR and hance 
--- Am excluding these patients from this Analysis


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_2 AS
SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1
WHERE ENROLID NOT IN ('20050861235', '20048536999', '20039580477', '20052475518', '20051103633')
;


SELECT COUNT(*) AS COUNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_2;

--COUNT	PATS
--9794	9794

SELECT *
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_2
LIMIT 10;

---===============================================================================---
---1.3. Patients with ≥1 claim with a diagnosis of emphysema (ICD-10-CM: J43.x) in 
---all available data (i.e., no time restrictions)
---===============================================================================---

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 AS
SELECT DISTINCT
    A.ENROLID,
    A.AATD_DX_DT,
    A.GENDER,
    A.DOBYR
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_2 A
INNER JOIN PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503 B
    ON A.ENROLID = B.ENROLID
WHERE B.DX LIKE 'J43%'  -- Emphysema ICD-10-CM codes
;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1;

--CNT	PATS
--2932	2932

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 LIMIT 10;


---======================================================================================================================---
---1.4. Patients whose first emphysema diagnosis occurs before or within 365 days following 
---the confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)
---======================================================================================================================---


---Step1 : Patient's first Emphysema :

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_FIRST_EMPHYSEMA_SG_1 AS
WITH EMPHYSEMA_DX AS (
    SELECT
        ENROLID,
        DX_DT,
        DX,
        ROW_NUMBER() OVER (PARTITION BY ENROLID ORDER BY DX_DT ASC) AS RN
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_DIAGNOSIS_EVENTS_ALL_INSURANCES_POS_FOR_REQUESTS_202503
    WHERE DX LIKE 'J43%'
)
SELECT
    C.ENROLID,
    C.AATD_DX_DT,
    C.GENDER,
    C.DOBYR,
    E.DX_DT AS FIRST_EMPHYSEMA_DX_DATE,
    E.DX
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_CLAIMS_SG_1 C
JOIN EMPHYSEMA_DX E
    ON C.ENROLID = E.ENROLID
WHERE E.RN = 1;

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_FIRST_EMPHYSEMA_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_FIRST_EMPHYSEMA_SG_1;

--CNT	PATS
--2932	2932

---Step2 : Finding confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_DIAG_CONFIRM_SG_1 AS
WITH AATD_CLAIMS AS (
    SELECT
        ENROLID,
        DX_DT,
        POS_CATEGORY
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503
    WHERE DX LIKE 'E8801%'
),
INPATIENT_CLAIMS AS (
    SELECT ENROLID, MIN(DX_DT) AS FIRST_INPATIENT_DATE
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY = 'ip'
    GROUP BY ENROLID
),
OUTPATIENT_CLAIMS AS (
    SELECT ENROLID, DX_DT
    FROM AATD_CLAIMS
    WHERE POS_CATEGORY IN ('op', 'er', 'other', 'ltc')
),
OUTPATIENT_PAIRS AS (
    SELECT
        A.ENROLID,
        MIN(A.DX_DT) AS FIRST_OUTPATIENT_DATE,
        MIN(B.DX_DT) AS SECOND_OUTPATIENT_DATE
    FROM OUTPATIENT_CLAIMS A
    JOIN OUTPATIENT_CLAIMS B
        ON A.ENROLID = B.ENROLID
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
    GROUP BY a.ENROLID
)
SELECT
    E.ENROLID,
    E.AATD_DX_DT,
    E.GENDER,
    E.DOBYR,
    E.FIRST_EMPHYSEMA_DX_DATE,
    I.FIRST_INPATIENT_DATE,
    O.FIRST_OUTPATIENT_DATE,
    O.SECOND_OUTPATIENT_DATE
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_FIRST_EMPHYSEMA_SG_1 E
LEFT JOIN INPATIENT_CLAIMS I ON E.ENROLID = I.ENROLID
LEFT JOIN OUTPATIENT_PAIRS O ON E.ENROLID = O.ENROLID
WHERE I.FIRST_INPATIENT_DATE IS NOT NULL
   OR O.SECOND_OUTPATIENT_DATE IS NOT NULL;


SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_DIAG_CONFIRM_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_DIAG_CONFIRM_SG_1;

--CNT	PATS
--2932	2932

---Step3 : Finding the patients whose first emphysema diagnosis occurs before or 
--within 365 days following the confirmatory AATD diagnosis (i.e., the first inpatient AATD diagnosis or the second eligible outpatient diagnosis)


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_EMPHYSEMA_TIMING_SG_1 AS
SELECT
    ENROLID,
    AATD_DX_DT,
    GENDER,
    DOBYR,
    FIRST_EMPHYSEMA_DX_DATE,
    FIRST_INPATIENT_DATE,
    SECOND_OUTPATIENT_DATE,
    CASE
        WHEN FIRST_EMPHYSEMA_DX_DATE <= DATEADD(day, 365, COALESCE(FIRST_INPATIENT_DATE, SECOND_OUTPATIENT_DATE))
        THEN 'YES'
        ELSE 'NO'
    END AS EMPHYSEMA_WITHIN_365_FLAG
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_DIAG_CONFIRM_SG_1
WHERE FIRST_EMPHYSEMA_DX_DATE <= DATEADD(day, 365, COALESCE(FIRST_INPATIENT_DATE, SECOND_OUTPATIENT_DATE));

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_EMPHYSEMA_TIMING_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_EMPHYSEMA_TIMING_SG_1
WHERE EMPHYSEMA_WITHIN_365_FLAG IN ('YES');

--CNT	PATS
--2640	2640


---============================================================================================================================---
---1.5. Patients with ≥1 inpatient or ≥2 outpatient claims (≥30 days apart and ≤365 days between) with a diagnosis of emphysema 
---index date is date of first emphysema diagnosis
---============================================================================================================================---

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1 AS
WITH EMPHYSEMA_CLAIMS AS (
    SELECT
        ENROLID,
        DX_DT,
        POS_CATEGORY
    FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503
    WHERE DX LIKE 'J43%'
),
INPATIENT_CLAIMS AS (
    SELECT ENROLID, MIN(DX_DT) AS FIRST_EMPHYSEMA_INPATIENT_DATE
    FROM EMPHYSEMA_CLAIMS
    WHERE POS_CATEGORY = 'ip'
    GROUP BY ENROLID
),
OUTPATIENT_CLAIMS AS (
    SELECT ENROLID, DX_DT
    FROM EMPHYSEMA_CLAIMS
    WHERE POS_CATEGORY IN ('op', 'er', 'other', 'ltc')
),
OUTPATIENT_PAIRS AS (
    SELECT
        A.ENROLID,
        MIN(a.DX_DT) AS FIRST_EMPHYSEMA_OUTPATIENT_DATE,
        MIN(b.DX_DT) AS SECOND_EMPHYSEMA_OUTPATIENT_DATE
    FROM OUTPATIENT_CLAIMS A
    JOIN OUTPATIENT_CLAIMS B
        ON A.ENROLID = B.ENROLID
     AND B.DX_DT > A.DX_DT
     AND DATEDIFF(DAY, A.DX_DT, B.DX_DT) BETWEEN 30 AND 365
    GROUP BY A.ENROLID
)
SELECT
    E.ENROLID,
    E.AATD_DX_DT,
    E.GENDER,
    E.DOBYR,
    E.FIRST_EMPHYSEMA_DX_DATE,
    I.FIRST_EMPHYSEMA_INPATIENT_DATE,
    O.FIRST_EMPHYSEMA_OUTPATIENT_DATE,
    O.SECOND_EMPHYSEMA_OUTPATIENT_DATE
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_PATS_EMPHYSEMA_TIMING_SG_1 E
LEFT JOIN INPATIENT_CLAIMS I ON E.ENROLID = I.ENROLID
LEFT JOIN OUTPATIENT_PAIRS O ON E.ENROLID = O.ENROLID
WHERE I.FIRST_EMPHYSEMA_INPATIENT_DATE IS NOT NULL
   OR O.SECOND_EMPHYSEMA_OUTPATIENT_DATE IS NOT NULL;


SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1 LIMIT 10;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1;

--CNT	PATS
--2144	2144

---====================================================================---
---1.6. Patients age ≥18 years on the date of first emphysema diagnosis---
---====================================================================---

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1 AS
SELECT DISTINCT
    ENROLID,
    AATD_DX_DT,
    GENDER,
    DOBYR,
    FIRST_EMPHYSEMA_DX_DATE,
    (YEAR(FIRST_EMPHYSEMA_DX_DATE) - DOBYR) AS AGE_AT_DIAGNOSIS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_IP_OP_CLAIMS_SG_1
WHERE (YEAR(FIRST_EMPHYSEMA_DX_DATE) - DOBYR) >= 18;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1;

--CNT	PATS
--2136	2136

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1 LIMIT 10;


---=========================================================================================================================---
---1.7. Patients with continuous enrollment throughout the 365-day baseline period and index date, allowing for ≤30-day gaps---
---=========================================================================================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503
LIMIT 10;

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_30d_GAP_SG_1 AS
WITH FIRST_EMPHYSEMA AS (
SELECT A.*, B.CONT_ENR_START_DT, B.CONT_ENR_END_DT
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1 AS A
INNER JOIN 
     PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503 AS B
   ON A.ENROLID = B.ENROLID
WHERE A.FIRST_EMPHYSEMA_DX_DATE BETWEEN B.CONT_ENR_START_DT AND B.CONT_ENR_END_DT
)
SELECT * 
FROM FIRST_EMPHYSEMA
WHERE DATEDIFF(DAY, CONT_ENR_START_DT, FIRST_EMPHYSEMA_DX_DATE) >= 365;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_30d_GAP_SG_1;

--CNT	PATS
--626	626

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_30d_GAP_SG_1 LIMIT 10;



---============================================================================================---
---1.8. Patients with continuous enrollment 365 days following the index date (no gaps allowed)---
---============================================================================================---

---------------------------------------------------------------------------------
-- generate a continuous enrollment dataset: any type of enrollment
---------------------------------------------------------------------------------
-- 0d allowable gap

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_ANY_CONTINUOUS_ENROLLMENT_0D_GAP_FOR_REQUESTS_202503 LIMIT 10;


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1 AS
WITH FIRST_EMPHYSEMA AS (
SELECT A.ENROLID, A.AATD_DX_DT, A.GENDER, A.DOBYR, A.FIRST_EMPHYSEMA_DX_DATE, A.AGE_AT_DIAGNOSIS, B.CONT_ENR_START_DT, B.CONT_ENR_END_DT
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_30d_GAP_SG_1 AS A
INNER JOIN 
     PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_ANY_CONTINUOUS_ENROLLMENT_0D_GAP_FOR_REQUESTS_202503 AS B
   ON A.ENROLID = B.ENROLID
WHERE A.FIRST_EMPHYSEMA_DX_DATE BETWEEN B.CONT_ENR_START_DT AND B.CONT_ENR_END_DT
)
SELECT * 
FROM FIRST_EMPHYSEMA
WHERE DATEDIFF(DAY, FIRST_EMPHYSEMA_DX_DATE, CONT_ENR_END_DT) >= 365;


SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1;

--CNT	PATS
--489	489
SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1 LIMIT 10;


---==================================================---
---1.9. Patients without a history of lung transplant---
---==================================================---

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_procedure_events_all_insurances_pos_for_requests_202503 LIMIT 10;


SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_procedure_events_all_insurances_pos_for_requests_202503
WHERE PROC IN ('32851')
LIMIT 10;

---Step1 : Looking in the Diagnosis table

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG_1 AS
SELECT A.*
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1 AS A
INNER JOIN 
PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 AS B
ON A.ENROLID = B.ENROLID
WHERE (B.DX LIKE '0BY%' 
   OR B.DX LIKE 'T868%'
   OR B.DX LIKE 'Z482%'
   OR B.DX LIKE 'Z942%')
  AND B.DX_DT <= FIRST_EMPHYSEMA_DX_DATE
;


---Step2 : Looking in the Procedure table

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG_2 AS
SELECT A.*
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1 AS A
INNER JOIN 
PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_procedure_events_all_insurances_pos_for_requests_202503 AS B
ON A.ENROLID = B.ENROLID
WHERE (B.PROC IN ('32851', '32852', '32853', '32854'))
  AND B.PROC_DT <= FIRST_EMPHYSEMA_DX_DATE
;


---Step3 : Getting the patients without the lung transplant


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG AS
WITH TBL1 AS (
SELECT DISTINCT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG_1
UNION ALL
SELECT DISTINCT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG_2
)
SELECT DISTINCT ENROLID, AATD_DX_DT, GENDER, DOBYR, FIRST_EMPHYSEMA_DX_DATE, AGE_AT_DIAGNOSIS
  FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_CONT_ENROL_0d_GAP_SG_1
  WHERE ENROLID NOT IN (SELECT DISTINCT ENROLID FROM TBL1)
;


SELECT COUNT(*) AS CNT, COUNt(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG;

--CNT	PATS
--484	484

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG LIMIT 10;


---=======================================================================---
---1.10. Patients without a diagnosis of Immunoglobulin A (IgA) deficiency---
---=======================================================================---


---Step1 : Looking in the Diagnosis table

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG_1 AS
SELECT A.*
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG AS A
INNER JOIN 
PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 AS B
ON A.ENROLID = B.ENROLID
WHERE (B.DX LIKE 'D802%')
  AND B.DX_DT <= FIRST_EMPHYSEMA_DX_DATE
;


---Getting the patients without IGA Difficiency
CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG AS
SELECT DISTINCT ENROLID, AATD_DX_DT, GENDER, DOBYR, FIRST_EMPHYSEMA_DX_DATE, AGE_AT_DIAGNOSIS
  FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LUNG_TRANS_SG
  WHERE ENROLID NOT IN (SELECT DISTINCT ENROLID FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG_1)
;


SELECT COUNT(*) AS CNT, COUNt(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG;

--CNT	PATS
--484	484

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG LIMIT 10;

---====================================================================---
---1.11. Patients without a diagnosis of liver disease or liver failure---
---====================================================================---


CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LIVER_SG_1 AS
SELECT A.*
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG AS A
INNER JOIN 
PRJ_XPLR_MKTSCAN_STD_A_STG.marketscan_std_a_diagnosis_events_all_insurances_pos_for_requests_202503 AS B
ON A.ENROLID = B.ENROLID
WHERE (B.DX LIKE 'K76%' 
   OR B.DX LIKE 'K74%'
   OR B.DX LIKE 'K75%'
   OR B.DX LIKE 'B18%'
   OR B.DX LIKE 'K70%'
   OR B.DX LIKE 'K72%'
   OR B.DX LIKE 'K73%'
   OR B.DX LIKE 'K71%'
   OR B.DX LIKE 'K77%')
  AND B.DX_DT <= FIRST_EMPHYSEMA_DX_DATE
;


---Getting the patients without Liver Disease
CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LIVER_SG AS
SELECT DISTINCT ENROLID, AATD_DX_DT, GENDER, DOBYR, FIRST_EMPHYSEMA_DX_DATE, AGE_AT_DIAGNOSIS
  FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IGA_SG
  WHERE ENROLID NOT IN (SELECT DISTINCT ENROLID FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LIVER_SG_1)
;


SELECT COUNT(*) AS CNT, COUNt(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LIVER_SG;

--CNT	PATS
--387	387

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_LIVER_SG LIMIT 10;

