---===============================================================---
---1.3. Patients age ≥18 years on the date of first AATD diagnosis---
---===============================================================---

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1 AS
SELECT DISTINCT
    A.ENROLID,
    A.AATD_DX_DT AS FIRST_AATD_DX_DATE,
    B.GENDER,
    B.DOBYR,
    (YEAR(A.AATD_DX_DT) - B.DOBYR) AS AGE_AT_DIAGNOSIS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_IP_OP_CLAIMS_SG_1 A
INNER JOIN PRJ_XPLR_MKTSCAN_STD_A_STG.MARKETSCAN_STD_A_MED_AND_RX_CONTINUOUS_ENROLLMENT_30D_GAP_FOR_REQUESTS_202503 B
    ON A.ENROLID = B.ENROLID
WHERE (YEAR(A.AATD_DX_DT) - B.DOBYR) >= 18;

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1;

--CNT	PATS
--8858	8856


SELECT *
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1
WHERE ENROLID IN ('20050861235', '20039580477')
;

---Here the above 2 patients recorded multiple Gender entries and hence I am excluding these 2 patients

CREATE OR REPLACE TABLE PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2 AS
SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_1
WHERE ENROLID NOT IN ('20050861235', '20039580477');

SELECT COUNT(*) AS CNT, COUNT(DISTINCT ENROLID) AS PATS
FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2;

--CNT	PATS
--8854	8854

SELECT * FROM PRJ_XPLR_MKTSCAN_STD_A_STG.AATD_EMP_PATS_AGE_SG_2 LIMIT 10;






